### ISSUE TITLE
Can't delete objects

### ISSUE THREAD

**Issue by AlecAivazis** [AlecAivazis/feynman#26]
@cshimmin commented on [Thu Jun 11 2015](https://github.com/AlecAivazis/feynman-old/issues/28)

Hey, cool project! According to the hotkey list, pressing backspace/delete should remove the selected object. However it just causes my browser to navigate back in history (which is of course the default browser action for this key). I'm using Chrome (43.0.2357.81) on OSX yosemite, and whatever version is running on your site: http://feynman.aivazis.com/

---

@cshimmin commented on [Thu Jun 11 2015](https://github.com/AlecAivazis/feynman-old/issues/28#issuecomment-111146857)

P.S. I'm starting from the example Drell-Yan diagram, not sure if that's relevant.

---

@cshimmin commented on [Thu Jun 11 2015](https://github.com/AlecAivazis/feynman-old/issues/28#issuecomment-111147092)

Also selecting the object and clicking the big red "Delete This Line" button does nothing.

---

@AlecAivazis commented on [Sat May 07 2016](https://github.com/AlecAivazis/feynman-old/issues/28#issuecomment-217663203)

Hey @cshimmin - First off, allow me to apologize, I'm really not sure why I wasn't "watching" my own project but I had no idea this bug was present until a few days ago. Unfortunately, I haven't been drawing many feynman diagrams lately. I've tried to go back and fix some things a few times but the backend codebase is rather scattered (this was one of my first web applications) and based on old versions of packages whose APIs drastically changed.

Good new though! After seeing your message, I decided enough was enough and migrated the application over to a [new](http://githubcom/AlecAivazis/feynman-node) server. The client codebase is the same (all features work as they did before), but hopefully this means I will be able to fix your issue very soon. I'll keep you updated. Sorry again for the year long wait.

---

@AlecAivazis commented on [Sun May 08 2016](https://github.com/AlecAivazis/feynman-old/issues/28#issuecomment-217755702)

I have fixed the bug in the new version and will have it deployed by the end of the day. Sorry again for letting this project slip away!

---

@AlecAivazis commented on [Sun May 08 2016](https://github.com/AlecAivazis/feynman-old/issues/28#issuecomment-217757921)

I'm moving this over to the new repo, I will leave that issue up until the new version is deploy since the problem was fixed.

**Comment by AlecAivazis** [comment]
Closing this since the new version has been published. Sorry again for the late response

**Comment by cshimmin** [comment]
Cool! Thanks for fixing. Just wanted to say thanks; I use your site all the time to make quick sketches to show in meetings at CERN :)
