### ISSUE TITLE
Improve text item

### ISSUE THREAD

**Issue by heitorPB** [AlecAivazis/feynman#29]
I can't write something like "W^+"
But "W^-" or "W_a" works. The "+" does not appear.
It would be nice to wrap the text field in a LaTeX environment.

**Comment by AlecAivazis** [comment]
Thanks for the reporting this.

The content of the text field is ran through pdflatex so it should work as you have it. I'll try to get a fix as soon as possible

**Comment by AlecAivazis** [comment]
@heitorPB I just deployed a fix for this issue. Thanks again for reporting it.
