### ISSUE TITLE
Labels vanish when exporting to png in Iceweasel 43.0.4

### ISSUE THREAD

**Issue by bjfar** [AlecAivazis/feynman#33]
And just as a side issue; the dragged corner of the "select" box does not align with the position of the mouse cursor. And a suggestion, it would be super useful to be able to copy/paste graph elements :). Nice concept though!

**Comment by AlecAivazis** [comment]
Thanks for the report @bjfar! This seems to be a problem across all browsers. I'm going to close this in order to keep things organized.
