### ISSUE TITLE
Text not exporting to png

### ISSUE THREAD

**Issue by alkaloge** [AlecAivazis/feynman#53]
Great tool! However, when exporting to png, text is not shown - using mac + mozilla

**Comment by AlecAivazis** [comment]
Ah damn, you are right. Sorry about that. I will see if I can figure out a solution. In the meantime, does a screenshot work to capture the diagram?

**Comment by AlecAivazis** [comment]
@alkaloge You should now be seeing text in exported pngs - please let me know if you run into any more problems.
