### ISSUE TITLE
Problem with Export PNG

### ISSUE THREAD

**Issue by ElemerNagy** [AlecAivazis/feynman#55]
I have drawn on the canvas a Feynman diagram, but when clicked on the button Export PNG the file created was empty. I am using MacBook Air macOS Sierra 10.12.3.
Also, I would like to know how can I save a Feynman diagram such that I could change/complete it in a successive session?

Thanks,

Elemer

**Comment by AlecAivazis** [comment]
Hey Elemer, thanks for submitting both issues. Since it seems your problem has changed, i'm going to close this issue and move the conversation there.
