### ISSUE TITLE
Download diagram as png: file corrupted

### ISSUE THREAD

**Issue by edbird** [AlecAivazis/feynman#81]
Not sure how the export to png is done, but on a linux system, with google chrome as a browser, no application (image viewer, gimp image editor) are able to open the png file.

**Comment by AlecAivazis** [comment]
Thanks for reporting this @edbird and i'm sorry for any inconveniences it's caused. I suspect this is related to the other issue you submitted and there might be a bug in the latex package - can you paste the diagram code here?

**Comment by AlecAivazis** [comment]
Since the problem was in the exported latex, not in the actual serving of the image, i'm going to close this issue and instead open a new one to improve error handling when exporting images. Thanks again for reporting the issue!
