### ISSUE TITLE
Saving as png does not preserve propagator direction

### ISSUE THREAD

**Issue by jardon-u** [AlecAivazis/feynman#85]
Arrows are not pointing the same direction in the exported image

**Comment by AlecAivazis** [comment]
Thanks for reporting this @jardon-u - I'll try to get a fix out before the end of the weekend

**Comment by AlecAivazis** [comment]
@jardon-u  i have submitted a fix which should now be published. Please let me know if you're still running into this issue.

**Comment by jardon-u** [comment]
Awesome 👍 it works
