### ISSUE TITLE
Dashed line arrow doesn't come out correctly when exporting to .png

### ISSUE THREAD

**Issue by thrichar** [AlecAivazis/feynman#94]
![diagram](https://user-images.githubusercontent.com/35909232/39221833-e5eb94e6-47fe-11e8-8940-3450d94d5531.png)

I've noticed that dashed lines have two arrows facing each other when the diagram is exported to a .png format.

**Comment by AlecAivazis** [comment]
Hey @thrichar - thanks for reporting this. I was able to verify the issue and will try to figure out the problem some time this week.
